model:
  name: 'TextDetectionModel'
  in_channels: 3 
  out_channels: 1
  init_filters: 64
  dropout_rate: 0.2

data:
  dataset_name: "mychen76/invoices-and-receipts_ocr_v2"  
  image_size: [512, 512]  
  data_dir: 'data/' 
  train_split: 0.8 
  val_split: 0.1 
  test_split: 0.1 
  num_workers: 4  
  max_samples: null
  cache_dir: null 

loss:
  text_map_weight: 1.0 
  box_weight: 0.1  
  confidence_weight: 0.5 

training:
  batch_size: 8  
  epochs: 10  
  learning_rate: 0.0001
  weight_decay: 0.0001  
  num_workers: 4  
  optimizer: "adam"  
  
  # Logging and visualization
  log_interval: 10  
  visualization_interval: 50  
  eval_interval: 1  
  save_interval: 5  
  
  # Learning rate scheduler
  use_scheduler: true  
  scheduler_type: "cosine_warmup" 
  warmup_epochs: 3  
  warmup_mult: 2  
  min_lr: 0.000001  

evaluation:
  confidence_threshold: 0.3
  iou_threshold: 0.3  
  max_boxes: 100  
  evaluate_f1: true 
  evaluate_precision: true
  evaluate_recall: true
  
inference:
  confidence_threshold: 0.4
  nms_threshold: 0.3  
  max_boxes: 100  

output:
  save_visualizations: true  
  save_model: true  
  save_best_f1: true 
  save_best_loss: true  
  output_dir: "outputs/detection" 